language: go
sudo: required
dist: xenial
sevices:
  - docker
go:
- 1.13.x

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config
    - GO111MODULE=on
    - CGO_ENABLED=0

stages:
  - name: build

jobs:
  include:
    - stage: build
      name: "Build and Test"
      install:
        - bash .travis/install-operator-sdk.sh
        - bash .travis/install-python.sh
        - bash .travis/install-minikube.sh
      script:
        - make build
        - make gen-api-fail-if-dirty
        - make test
        - make test-integ
