apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  name: default
  labels:
    app: noobaa
spec:
  placementPolicy:
    tiers:
      - tier:
          mirrors:
            - mirror:
                spread:
                  - aws1
