apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: noobaa.noobaa.io:auth-delegator
subjects:
  - kind: ServiceAccount
    name: noobaa
    namespace: noobaa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
