apiVersion: apps/v1
kind: Deployment
metadata:
  name: noobaa-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      noobaa-operator: deployment
  template:
    metadata:
      labels:
        app: noobaa
        noobaa-operator: deployment
    spec:
      serviceAccountName: noobaa-operator
      containers:
        - name: noobaa-operator
          image: noobaa/noobaa-operator:1.1.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: OPERATOR_NAME
              value: noobaa-operator
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
