apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-noobaa-operator
  namespace: my-noobaa-operator
spec:
  channel: alpha
  name: noobaa-operator
  source: noobaa-operator
  sourceNamespace: olm
