apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: noobaa-operator-subscription
  namespace: my-noobaa-operator
spec:
  channel: alpha
  name: noobaa-operator
  source: noobaa-operator-source
  sourceNamespace: marketplace
