apiVersion: v1
kind: Service
metadata:
  name: SYSNAME-mgmt
  labels:
    app: noobaa
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: http
    prometheus.io/port: "8080"
spec:
  type: LoadBalancer
  selector:
    noobaa-mgmt: SYSNAME
  ports:
    - port: 8080
      name: mgmt
    - port: 8443
      name: mgmt-https
    - port: 8444
      name: md-https
    - port: 8445
      name: bg-https
    - port: 8446
      name: hosted-agents-https
    - port: 80
      targetPort: 6001
      name: s3
    - port: 443
      targetPort: 6443
      name: s3-https
