name: Weekly Build

# Run the Weekly on Monday 8:15 AM UTC
on:
  schedule:
    - cron: "15 8 * * 1"

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Prepare Tags
        id: prep
        run: |
          DOCKER_OPERATOR_IMAGE=noobaa/noobaa-operator
          VERSION="${{ steps.date.outputs.date }}"
          echo "::warning ${VERSION}"
          echo ::set-output name=version::${VERSION}
          OPERATOR_TAGS="${DOCKER_OPERATOR_IMAGE}:master-${VERSION}"          
          echo "::warning ${CORE_TAGS}"
          echo ::set-output name=operatortags::${OPERATOR_TAGS}

      - name: Update Core Release
        id: update-release
        run: |
          curl --silent -f -lSL "https://index.docker.io/v1/repositories/noobaa/noobaa-core/tags/master-${{ steps.prep.outputs.version }}" > /dev/null || exit 1
          echo "::found version ${{ steps.prep.outputs.version }}, updating image version"

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.GHACTIONSDOCKERHUB }} | docker login -u ${{ secrets.GHACTIONSDOCKERHUBNAME }} --password-stdin

      - name: Update Core Release Image
        id: update-release-image
        run: |
          # docker pull "noobaa/noobaa-core:master-${{ steps.prep.outputs.version }}"
          echo "::found version ${{ steps.prep.outputs.version }}, updating image version in options.go"
          # Update local files
          sed -i 's:ContainerImageTag =.*:ContainerImageTag = master-${{ steps.prep.outputs.version }}:' pkg/options/options.go

          # Commit Changes
          # git config --local user.email "action@github.com"
          # git config --local user.name "GitHub Action"
          # git commit -m "Auto update core image" -a

      - name: Build & Push Docker Image
        env:
          DOCKERHUB_OWNER: ${{ secrets.GHACTIONSDOCKERHUBNAME }}
        run: |
            make image VERSION=latest
            docker tag  noobaa-operator ${{ steps.prep.outputs.operatortags }}
            docker push ${{ steps.prep.outputs.operatortags }}

      - name: Push CLI Binary
        run: |
            make cli
            #noobaa-operator-cli

            date=`date +%Y%m%d`
            dateFormatted=`date -R`
            s3Bucket="noobaa-operator-cli"
            fileName="FILE_NAME"
            relativePath="/${s3Bucket}/${fileName}"
            contentType="application/octet-stream"
            stringToSign="PUT\n\n${contentType}\n${dateFormatted}\n${relativePath}"
            s3AccessKey="${{ secrets.AWSACCESSKEY }}"
            s3SecretKey="${{ secrets.AWSSECRETKEY }}"
            signature=`echo -en ${stringToSign} | openssl sha1 -hmac ${s3SecretKey} -binary | base64`
            curl -X PUT -T "${fileName}" \
            -H "Host: ${s3Bucket}.s3.amazonaws.com" \
            -H "Date: ${dateFormatted}" \
            -H "Content-Type: ${contentType}" \
            -H "Authorization: AWS ${s3AccessKey}:${signature}" \
            http://${s3Bucket}.s3.amazonaws.com/${fileName}
            

